# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opengyver < Formula
  desc "Swiss-army-knife CLI for everyday conversions — images, units, currencies, documents, time, and more"
  homepage "https://github.com/create-flow-ai/openGyver"
  version "1.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.1.2/openGyver_darwin_amd64.tar.gz"
      sha256 "8d4f8128afd4be0b85269ab7ad9c15c821a1910e13b64ef57acc640bcf4d187f"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.1.2/openGyver_darwin_arm64.tar.gz"
      sha256 "82cdfa5fcfd273b176fca99fd7936fb203594fd1ee5b4429e27f4dfc2e75d562"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.1.2/openGyver_linux_amd64.tar.gz"
      sha256 "8fde3b73b660141e65de12ab812eddfe8f203f3f2d0df0be4ac0b7e4503eaee7"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.1.2/openGyver_linux_arm64.tar.gz"
      sha256 "81ff986cea9ec292986ef9a5fdceb5bd22d7923005221236ed52464041f7a15f"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  test do
    system "#{bin}/openGyver", "--help"
    system "#{bin}/openGyver", "epoch"
    system "#{bin}/openGyver", "uuid"
  end
end
