# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opengyver < Formula
  desc "Swiss-army-knife CLI for everyday conversions — images, units, currencies, documents, time, and more"
  homepage "https://github.com/create-flow-ai/openGyver"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.2.0/openGyver_darwin_amd64.tar.gz"
      sha256 "638c71e14024ea126839ae5fbbb8b34bfa411ac0a65ea170f305f270a919a8d2"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.2.0/openGyver_darwin_arm64.tar.gz"
      sha256 "0be0ea4951c24e4cf50e4b3db7cddc31e471e51b74b74994e5e46716d538f845"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.2.0/openGyver_linux_amd64.tar.gz"
      sha256 "57366ad51deb49ef2bb9dc643926ebcc7c15a21764cd63ed23a0f76f04efa1a2"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v1.2.0/openGyver_linux_arm64.tar.gz"
      sha256 "8680d5054820d78d4603c4c7a3c9ce9bbd8aa48847fa307b2864e8ecbe63cd7e"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  test do
    system "#{bin}/openGyver", "--help"
    system "#{bin}/openGyver", "epoch"
    system "#{bin}/openGyver", "uuid"
  end
end
