# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opengyver < Formula
  desc "Swiss-army-knife CLI for everyday conversions — images, units, currencies, documents, time, and more"
  homepage "https://github.com/create-flow-ai/openGyver"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v0.1.2/openGyver_darwin_amd64.tar.gz"
      sha256 "f71e467cc5c7c1b4f990ca82c03e21dea042644ae60006b9fed08ef954de0428"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v0.1.2/openGyver_darwin_arm64.tar.gz"
      sha256 "78990bf5ab09ef6fa348eca037b0e27b44c18c47cd346a75e5393b8cfc6d106b"

      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v0.1.2/openGyver_linux_amd64.tar.gz"
      sha256 "82ff020d49ebdb505d16f9b801bfaaaba7c5c1b1d16f9a1e265026622c32353c"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/create-flow-ai/openGyver/releases/download/v0.1.2/openGyver_linux_arm64.tar.gz"
      sha256 "c0ac152be21e931fcbaffecf6d31338b6b25b815a1a208f1deae66a445bb5fdd"
      define_method(:install) do
        bin.install "openGyver"
      end
    end
  end

  test do
    system "#{bin}/openGyver", "--help"
    system "#{bin}/openGyver", "epoch"
    system "#{bin}/openGyver", "uuid"
  end
end
